version: '3'

services:
  app:
    container_name: backend
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - queue
      - cache

  queue:
    image: redis:7.2.4
    container_name: redis_queue
    restart: unless-stopped
    ports:
      - "6390:6379"
    volumes:
      - queue_data:/data

  cache:
    image: redis:7.2.4
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6391:6379"
    volumes:
      - cache_data:/data

volumes:
  queue_data:
  cache_data:
