import { Ean } from "@modules/comercial/produtos/models/ean.model";
import Divergencia from "../../../models/divergencia.model";

export default interface ProdutoDTO {
  id: number;
  codigo_produto_fornecedor: string;
  descritivo: string;
  descritivo_pdv: string;
  classificacao_fiscal: string;
  origem: string;
  estado: number;
  marca: number;
  depto: number;
  secao: number;
  grupo: number;
  subgrupo: number;
  preco: number;
  desconto_p: number;
  pesob: number;
  pesol: number;
  altura: number;
  largura: number;
  comprimento_d?: number;
  largura_d?: number;
  altura_d?: number;
  comprimento: number;
  validade: number;
  qtde_embalagem: number;
  comprador: number;
  categoria_fiscal: string;
  produto_arius: number;
  fornecedor_id: number;
  st_compra: string;
  tipo_tributacao: string;
  ipi: number;
  icms_compra: number;
  pis_cofins: string;
  eans: Ean[];
  duns: Ean[];
  divergencias: Divergencia[];
  status: number;
  familia: number;
  cadastro_arius?: Date;
  created_at?: Date;
}
